# Generated by Django 3.0.1 on 2022-09-04 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kilnkeeperconsole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kp', models.IntegerField()),
                ('Ki', models.IntegerField()),
                ('Kd', models.IntegerField()),
                ('Interval', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerInLine', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('Schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kilnkeeperconsole.Schedule')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('note', models.CharField(max_length=500)),
                ('Schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kilnkeeperconsole.Schedule')),
            ],
        ),
    ]
