# Generated by Django 3.0.1 on 2022-09-04 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kilnkeeperconsole', '0002_history_settings_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='cost',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='Firing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('target', models.FloatField()),
                ('error', models.FloatField()),
                ('p', models.FloatField()),
                ('i', models.FloatField()),
                ('d', models.FloatField()),
                ('pid', models.FloatField()),
                ('coil_on', models.FloatField()),
                ('coil_of', models.FloatField()),
                ('firing_time', models.FloatField()),
                ('time_left', models.FloatField()),
                ('History', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kilnkeeperconsole.History')),
            ],
        ),
    ]
