# Generated by Django 3.0.1 on 2022-09-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilnkeeperconsole', '0003_auto_20220904_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='KilnSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kp', models.IntegerField()),
                ('Ki', models.IntegerField()),
                ('Kd', models.IntegerField()),
                ('Interval', models.FloatField()),
                ('Max_kiln_temperature', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
