# Generated by Django 3.0.1 on 2022-09-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilnkeeperconsole', '0004_auto_20220904_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualKilnStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualTemperature', models.FloatField()),
                ('firing', models.BooleanField()),
            ],
        ),
    ]
